# k8s/app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: demo
spec:
  selector:
    app: springboot-app
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
