apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        env:
        # 1) Specify the DB to initialize (creates 'mydatabase')
        - name: MONGO_INITDB_DATABASE
          value: mydatabase

        # 2) Create your user in that database
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: password

        volumeMounts:
        - name: data
          mountPath: /data/db
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mongo-pvc
